### ISSUE TITLE
[MCHANGES-173] Failed to generate report when version is not the last schedule.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#156]
**[Christophe Richard](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christophe)** opened **[MCHANGES-173](https://issues.apache.org/jira/browse/MCHANGES-173?redirect=false)** and commented

We try to release a snapshot version (1.2.3-SNAPSHOT) but this version is not define as last release into JIRA version.
into JIRA we have define version as this (by schedule order)
* 1.3.0
* 1.2.3
* 1.2.2
  ....

When we try to generate jira report for e version 1.2.3-SNAPSHOT we have this error: (i don't if it occurs during jira report or annoucement)
PS: if i schedule 1.2.3 in first position into JIRa, it works fine.

```
...
[DEBUG] Default ResourceManager initialization complete.
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[DEBUG] Created '20' parsers.
[DEBUG] Velocimacro : initialization starting.
[DEBUG] Velocimacro : allowInline = true : VMs can be defined inline in templates
[DEBUG] Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions
[DEBUG] Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.
[DEBUG] Velocimacro : autoload off : VM system will not automatically reload global library macros
[DEBUG] Velocimacro : Velocimacro : initialization complete.
[DEBUG] RuntimeInstance successfully initialized.
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-changes-plugin:2.1:announcement-generate' -->
[DEBUG]   (s) artifactId = feedapi
[DEBUG]   (f) basedir = C:\HOMEWARE\eclipse-341\workspace\feedapi
[DEBUG]   (s) developmentTeam = vol-domino-feedapi team
[DEBUG]   (s) finalName = feedapi-1.2.3-SNAPSHOT
[DEBUG]   (f) generateJiraAnnouncement = true
[DEBUG]   (s) groupId = ged.domino
[DEBUG]   (s) introduction = FeedAPI is a framework to send feed between component (In and Out process) with high frequency const
aint
[DEBUG]   (f) jiraMerge = false
[DEBUG]   (f) jiraXML = C:\HOMEWARE\eclipse-341\workspace\feedapi\target\jira-announcement.xml
[DEBUG]   (f) maxEntries = 25
[DEBUG]   (s) outputDirectory = C:\HOMEWARE\eclipse-341\workspace\feedapi\target\announcement
[DEBUG]   (s) packaging = jar
[DEBUG]   (f) project = MavenProject: ged.domino:feedapi:1.2.3-SNAPSHOT @ C:\HOMEWARE\eclipse-341\workspace\feedapi\pom.xml
[DEBUG]   (f) resolutionIds = Fixed
[DEBUG]   (f) settings = org.apache.maven.settings.Settings@1eb62b6
[DEBUG]   (f) statusIds = Closed
[DEBUG]   (f) template = feedapi-announcement.vm
[DEBUG]   (f) templateDirectory = our-announcements
[DEBUG]   (s) url = http://frontools/maven_site/domino-parent/feedapi
[DEBUG]   (s) version = 1.2.3-SNAPSHOT
[DEBUG]   (s) xmlPath = C:\HOMEWARE\eclipse-341\workspace\feedapi\src\changes\changes.xml
[DEBUG] -- end configuration --
[INFO] [changes:announcement-generate {execution: announcement-generate}]
[DEBUG] JIRA lives at: https://jtbox.fr.world.socgen/jira
[DEBUG] The JIRA URL https://jtbox.fr.world.socgen/jira/browse/TRAFEEDAPI doesn't include a pid, trying to extract it from JIRA.
[DEBUG] Successfully reached JIRA.
26 ao¹t 2009 10:54:10 org.apache.commons.httpclient.HttpMethodBase getResponseBody
ATTENTION: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[DEBUG] Found the pid 10236 at https://jtbox.fr.world.socgen/jira/browse/TRAFEEDAPI
[ERROR] maven-changes-plugin: None of the configured sortColumnNames 'null' are correct.
[DEBUG] download jira issues from url https://jtbox.fr.world.socgen/jira/secure/IssueNavigator.jspa?view=rss&pid=10236&statusIds=
&resolutionIds=1&tempMax=25&reset=true&decorator=none
[INFO] Downloading from JIRA at: https://jtbox.fr.world.socgen/jira/secure/IssueNavigator.jspa?view=rss&pid=10236&statusIds=6&res
lutionIds=1&tempMax=25&reset=true&decorator=none
26 ao¹t 2009 10:54:10 org.apache.commons.httpclient.HttpMethodBase getResponseBody
ATTENTION: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[DEBUG] Downloading from JIRA was successful
[INFO] Creating announcement file from JIRA releases...
[DEBUG] Found 5 releases.
[DEBUG] The release: 1.1.0 has 1 actions.
[DEBUG] The release: 1.3.0 has 12 actions.
[DEBUG] The release: 1.2.1 has 6 actions.
[DEBUG] The release: 1.2.2 has 1 actions.
[DEBUG] The release: 1.2.0 has 4 actions.
[DEBUG] The release: 1.1.0 has 1 actions.
[DEBUG] The release: 1.3.0 has 12 actions.
[DEBUG] The release: 1.2.1 has 6 actions.
[DEBUG] The release: 1.2.2 has 1 actions.
[DEBUG] The release: 1.2.0 has 4 actions.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Couldn't find the release '1.2.3' among the supplied releases.
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Couldn't find the release '1.2.3' among the supplied releases.
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:703)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Couldn't find the release '1.2.3' among the supplied releases.
        at org.apache.maven.plugin.announcement.AnnouncementMojo.getLatestRelease(AnnouncementMojo.java:460)
        at org.apache.maven.plugin.announcement.AnnouncementMojo.doGenerate(AnnouncementMojo.java:349)
        at org.apache.maven.plugin.announcement.AnnouncementMojo.doJiraGenerate(AnnouncementMojo.java:582)
        at org.apache.maven.plugin.announcement.AnnouncementMojo.execute(AnnouncementMojo.java:335)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
        ... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20 seconds
[INFO] Finished at: Wed Aug 26 10:54:11 CEST 2009
[INFO] Final Memory: 29M/52M
[INFO] ------------------------------------------------------------------------
```

extract of our pom:

```xml
....
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-changes-plugin</artifactId>
				<version>2.1</version>
				<executions>
					<execution>
						<id>announcement-generate</id>
						<phase>deploy</phase>
						<goals>
							<goal>announcement-generate</goal>
							<goal>announcement-mail</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<template>my-announcement.vm</template>
					<templateDirectory>our-announcements</templateDirectory>

					<generateJiraAnnouncement>true</generateJiraAnnouncement>
					<xmlPath>${basedir}/src/changes/changes.xml</xmlPath>
					<smtpHost>smtp-gw</smtpHost>
					<smtpPort>25</smtpPort>
					<mailContentType>text/html</mailContentType>
					<mailSender>
						<name>foo</name>
						<email>foo.bar@foobar.com</email>
					</mailSender>

					<!-- For JIRA-report -->
					<columnNames>Type,Key,Summary,Assignee,Status,Resolution,Fix Version</columnNames>
					<onlyCurrentVersion>false</onlyCurrentVersion>
					<filter>statusIds%3D6%26statusIds%3D5%26resolutionIds%3D1%26sorter%2Ffield%3Dissuekey%26sorter%2Forder%3DASC%26sorter%2Ffield%3Dissuetype%26sorter%2Forder%3DASC</filter>
					<sortColumnNames>Fix Version,Type,Key</sortColumnNames>
					<reportSets>
						<reportSet>
							<reports>
								<report>jira-report</report>
							</reports>
						</reportSet>
					</reportSets>
					<toAddresses>
						<toAddress>jonh.smith@bigcompany.com</toAddress>
					</toAddresses>
				</configuration>
			</plugin>
```

---

**Affects:** 2.1

4 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

You probably need to increase maxEntries in your POM configuration for the plugin. The default value is 25, meaning that only 25 issues is fetched. Try something like this:

```xml
<configuration>
  <maxEntries>100</maxEntries>
</configuration>
```

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

You are probably hitting the limit of max 25 issues specified by the "maxEntries" parameter. This limits the amount of issues that the plugin will fetch from JIRA. If you have a lot of issues (more than 25) in your 1.3.0 release, this can happen.

Please try to increase the value of "maxEntries" in your configuration.

We should probably increase the default value from 25 to something higher.

**Comment by jira-importer** [comment]
**[Christophe Richard](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christophe)** commented

Hi Dennis,

All release together we have more than 25 entries, but concerning the 1.3.0 just 2-3 issues.
So i'll do the test asap.
