### ISSUE TITLE
[MCHANGES-175] Allow accessing JIRA instances that use untrusted certificates

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#158]
**[Krishna Pothula](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kpothula)** opened **[MCHANGES-175](https://issues.apache.org/jira/browse/MCHANGES-175?redirect=false)** and commented

We have an intranet Jira setup with https to have integration with LDAP. The certificate used is an internal one not issued by any CA.

While accessing this repository jira-report throws below Exception:

---

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:150)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1476)
at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:174)
at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:168)
at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:847)
at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:106)
at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Handshaker.java:495)
at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Handshaker.java:433)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:815)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1025)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:619)
at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:59)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:827)
at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:1975)
at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:993)
at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
at org.apache.maven.plugin.jira.JiraHelper.getPidFromJira(JiraHelper.java:55)
at org.apache.maven.plugin.jira.AbstractJiraDownloader.doExecute(AbstractJiraDownloader.java:363)
at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:245)

---

---

**Affects:** 2.1

**Attachments:**
- [patch_MCHANGES-175.diff](https://issues.apache.org/jira/secure/attachment/12714492/patch_MCHANGES-175.diff) (_17.44 kB_)

**Issue Links:**
- [MCHANGES-200](https://issues.apache.org/jira/browse/MCHANGES-200) Problem with login to jira over https and proxy
 (_**"is duplicated by"**_)

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Krishna Pothula](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kpothula)** commented

And the root cause is...

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:236)
at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:194)
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:216)

**Comment by jira-importer** [comment]
**[Krishna Pothula](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kpothula)** commented

Attached is the Patch that'll fix the bug.

In this patch a new plugin property is introduced "acceptUntrustedCert". If this property is set to true then this plugin will work with self-signed or untrusted SSL certificates.

I sincerely hope this will be added to the 2.2 version of this plugin.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Lowering priority on this issue as there are work-arounds available. Either add the cert to the JDK trust store or get a cert that can be validated by the JDK's available root certs.

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

Unfortunately, this patch has gone stale due to intervening changes.

Could you possibly update it?

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

No response in over six months, problem with workaround, closing.
