### ISSUE TITLE
[MCHANGES-285] SAXException parsing JIRA XML from JIRA 5.1 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#173]
**[Micah Whitacre](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkwhitacre)** opened **[MCHANGES-285](https://issues.apache.org/jira/browse/MCHANGES-285?redirect=false)** and commented

When trying to generate a changes report from a JIRA instance running 5.1[1] I get the following exception

[INFO] Generating "JIRA Report" report    --- maven-changes-plugin:2.7.1
Jul 16, 2012 5:32:53 PM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[INFO] Downloading from JIRA at: http://bugs.cloud.cerner.corp/secure/IssueNavigator.jspa?view=rss&pid=10670&component=kepler-client&component=kepler-parent&status=Verified&status=Closed&resolution=1&resolution=12&tempMax=100&reset=true&decorator=none
[WARNING]
org.apache.maven.plugin.MojoExecutionException: Failed to parse JIRA XML.
at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:132)
at org.apache.maven.plugin.jira.JiraXML.parseXML(JiraXML.java:108)
at org.apache.maven.plugin.jira.AbstractJiraDownloader.getIssueList(AbstractJiraDownloader.java:755)
at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:347)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:317)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.
at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
at org.apache.xerces.impl.XMLScanner.scanAttributeValue(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanAttribute(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:128)
... 30 more

[1] - https://confluence.atlassian.com/display/JIRA/JIRA+5.1+Release+Notes

---

**Affects:** 2.7.1

**Attachments:**
- [patch.txt](https://issues.apache.org/jira/secure/attachment/12714580/patch.txt) (_47.52 kB_)
- [patch-2.7.x.txt](https://issues.apache.org/jira/secure/attachment/12714658/patch-2.7.x.txt) (_47.83 kB_)

**Issue Links:**
- [MCHANGES-263](https://issues.apache.org/jira/browse/MCHANGES-263) Add support for JQL introduced in JIRA 4.x
 (_**"supercedes"**_)

5 votes, 11 watchers

**Comment by jira-importer** [comment]
**[Cristiano Andrade](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cristiano.andrade@wba.com.br)** commented

I have same problem! Is there a solution for that?

**Comment by jira-importer** [comment]
**[Gary Clayburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gclayburg)** commented

I seem to be having a very similar problem.  Maybe this issue is related to our use of Jira on demand?

**Comment by jira-importer** [comment]
**[Jamie Duncombe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jamied)** commented

I am also able to confirm that I'm seeing this problem using a Jira 5.1 hosted by Atlassian OnDemand, project was previously working on Jira 4.1.3 download edition.

Viewing the generated URL from my stack trace in a web browser I can confirm that the page returned is not in XML format but is the html page without decoration, in my case at least it does return the correct results for the JQL query.

URL generated:
https://{jira instance address removed for security}/secure/IssueNavigator.jspa?view=rss&pid=10680&statusIds=1&statusIds=3&statusIds=4&statusIds=5&statusIds=6&resolutionIds=-1&resolutionIds=1&resolutionIds=2&resolutionIds=3&resolutionIds=4&resolutionIds=5&component=11750&sorter/field=created&sorter/order=DESC&sorter/field=priority&sorter/order=DESC&tempMax=100&reset=true&decorator=none

A working URL obtained by requesting the xml (rss 0.9.2) format from the above page:

https://{jira instance address removed for security}/sr/jira.issueviews:searchrequest-xml/temp/SearchRequest.xml?jqlQuery=project+%3D+TOOLS+AND+component+%3D+toolname+ORDER+BY+created+DESC%2C+priority+DESC&tempMax=100

Hope this helps,

Jamie

**Comment by jira-importer** [comment]
**[Ton Swieb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tonswieb)** commented

I have the same issue with Jira 5.1 and created a patch for it.
The patch is based on the trunk.

I notice that at least since Jira 4.4.1 the URL's generated by this plugin are rewritten by JIRA to a new type of URL based on JQL (Jira Query Language) en probably since Jira 5.1 they have removed supported for the old type of URL.

The patch adds a new configuration flag "useJql" which can be enabled to query for issues using JQL, but defaults to false for backwards compatibility.

The issue management URL must be of the form:
http(s)://host:port/browse/{projectname} because JQL uses the project name instead of the project ID for constructing the query.

All other configuration parameters should work in the same way.

**Comment by jira-importer** [comment]
**[Gary Clayburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gclayburg)** commented

Ton,

Thank your for attaching this patch.  I was able to install the patch and build the plugin.  However, I am getting this new error:

```
$ mvn  -f pom-changestest.xml changes:jira-report
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building changes-tests 1.22
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-changes-plugin:2.7.1:jira-report (default-cli) @ changes-tests ---
[WARNING] Deprecated API called - not org.apache.maven.doxia.sink.Sink instance and no SinkFactory available. Please update this plugin.
Aug 6, 2012 6:29:48 PM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[ERROR] Unable to extract a JIRA pid from the page at the url https://urlremoved.jira.com/browse/OIAM
[ERROR] Error accessing https://urlremoved.jira.com/browse/OIAM
java.lang.RuntimeException: The issue management URL in the POM does not include a pid, and it was not possible to extract it from the page at that URL.
        at org.apache.maven.plugin.jira.AbstractJiraDownloader.getParameterBasedQueryURL(AbstractJiraDownloader.java:230)
        at org.apache.maven.plugin.jira.AbstractJiraDownloader.doExecute(AbstractJiraDownloader.java:144)
        at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:354)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:144)
        at org.apache.maven.plugin.changes.AbstractChangesReport.execute(AbstractChangesReport.java:187)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[WARNING]
org.apache.maven.plugin.MojoExecutionException: Failed to parse JIRA XML.
        at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:132)
```

This is the slimmed down pom file I am using:

```
<?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <groupId>com.urlremoved</groupId>
        <artifactId>changes-tests</artifactId>
        <packaging>jar</packaging>
        <name>changes-tests</name>
        <version>1.22</version>
        <issueManagement>
            <system>JIRA</system>
            <url>https://urlremoved.jira.com/browse/OIAM</url>
        </issueManagement>
        <build>
            <finalName>changes-tests</finalName>
    
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-changes-plugin</artifactId>
                    <version>2.7.1</version>
                    <configuration>
                        <useJql>true</useJql>
                        <fixVersionIds>1.0.5</fixVersionIds>
                        <jiraUser>gary.clayburg@urlremoved.com</jiraUser>
                        <jiraPassword>password1234</jiraPassword>
                    </configuration>
                </plugin>
            </plugins>
    
        </build>
        <reporting>
            <plugins>
            </plugins>
        </reporting>
        <dependencies>
        </dependencies>
    
    </project>
```

Do I have this configured correctly?

**Comment by jira-importer** [comment]
**[Jamie Duncombe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jamied)** commented

Hi Gary,

The error you are seeing is because you have applied the patch to the 2.7.1 tag source code (there have been changes in the trunk to how the annotations are specified which are not backward compatible with the 2.7.1 codebase). I'm attaching a slight variation of the patch to fix this issue.  It will also update the pom to build a 2.7.2 version of the pom so you should update your client project to match this.

Let me know if you run into any problems,

Jamie

**Comment by jira-importer** [comment]
**[Gary Clayburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gclayburg)** commented

I finally got back to looking at this issue.  This patch worked great for me.  Thanks for the help, guys.

So what is the process for getting this patch committed and and released?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Thanks for the patch. I'll have a closer look at it.

Unfortunately it contains both refactorings and new functionality. It can be quite difficult to read such a patch, but I'll give it a try.

**Comment by jira-importer** [comment]
**[Ton Swieb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tonswieb)** commented

Hi Dennis,

Let me know if you need any help with the patch.

**Comment by jira-importer** [comment]
**[Gary D. Gregory](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=garydgregory)** commented

This issue shows up in some of the Apache Commons components. Is a bug fix release planned?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Patch applied in [r1379870](http://svn.apache.org/viewvc?view=revision&revision=1379870), [r1379884](http://svn.apache.org/viewvc?view=revision&revision=1379884) and [r1379888](http://svn.apache.org/viewvc?view=revision&revision=1379888).

After that I've made additional changes to adapt the new code to our conventions.

Thank you very much for the patch!

If you submit more patches in the future please make sure that you follow our coding conventions http://maven.apache.org/developers/conventions/code.html

I've deployed a new 2.8-SNAPSHOT in our SNAPSHOT Repository. Please verify that it works for you.

**Comment by jira-importer** [comment]
**[Ton Swieb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tonswieb)** commented

Thanks for applying the patch. It works for me. I will keep the coding conventions in mined for further patches.

Have you planned on releasing a 2.7 fix version for it or will it only be released as part of 2.8?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

It will be a 2.8 release.

**Comment by jira-importer** [comment]
**[Jaroslaw Cwiklik](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cwiklik)** commented

Any idea when the 2.8 releases? The problem fixed here is a blocker for Apache UIMA-AS release. Any chance of getting this released on a quick turn-around? Thanks.

**Comment by jira-importer** [comment]
**[Gary D. Gregory](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=garydgregory)** commented

FWIW: This is also breaking the JIRA report for the Apache Commons Codec 1.7 release under VOTE now, but we are proceeding regardless.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Yes, I'm working on getting the 2.8 release out.

**Comment by jira-importer** [comment]
**[Jaroslaw Cwiklik](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cwiklik)** commented

Thanks for the update. Do you think you are days or weeks away from releasing 2.8?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

I've just started the VOTE thread on dev@maven.a.o. If all goes well the release is ~72 hours away.
Please join us on the mailing list and cast your vote, if you have the possibility to test the release.

**Comment by jira-importer** [comment]
**[Gary Gregory](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ggregory)** commented

I still get this in 2.8:

```
[INFO] Generating "JIRA Report" report    --- maven-changes-plugin:2.8
Sep 17, 2012 8:54:14 PM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[INFO] Downloading from JIRA at: http://issues.apache.org/jira/secure/IssueNavigator.jspa?view=rss&pid=12310464&statusIds=5&statusIds=6&resolutionIds=1&type=1&t
ype=2&type=3&type=4&type=5&type=6&sorter/field=fixVersions&sorter/order=DESC&sorter/field=issuetype&sorter/order=ASC&sorter/field=issuekey&sorter/order=DESC&tem
pMax=100&reset=true&decorator=none
[WARNING]
org.apache.maven.plugin.MojoExecutionException: Failed to parse JIRA XML.
        at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:132)
        at org.apache.maven.plugin.jira.JiraXML.parseXML(JiraXML.java:108)
        at org.apache.maven.plugin.jira.AbstractJiraDownloader.getIssueList(AbstractJiraDownloader.java:608)
        at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:356)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
        at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
        at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.scanAttributeValue(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanAttribute(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:128)
        ... 30 more
```

This is with Apache Commons Codec trunk.

**Comment by jira-importer** [comment]
**[Micah Whitacre](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkwhitacre)** commented

I had the same problem until I shifted to using the \<useJql/> configuration which is required for JIRA 5.1 or higher.[1]

[1] - http://maven.apache.org/plugins/maven-changes-plugin/jira-report-mojo.html#useJql

**Comment by jira-importer** [comment]
**[Gary Clayburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gclayburg)** commented

Hey guys, this issue was working for me using Jira OnDemand.  It now appears to fail with this 400 error.  I'm thinking this is due to recent changes in the way that Jira OnDemand is doing authentication.  I get a similar error in a browser if the session is not authenticated.  Does anyone else use Jira OnDemand with this plugin?

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building changes-tests 1.22
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-changes-plugin:2.8-SNAPSHOT:jira-report (default-cli) @ changes-tests ---
[WARNING] Deprecated API called - not org.apache.maven.doxia.sink.Sink instance and no SinkFactory available. Please update this plugin.
[INFO] Downloading from JIRA at: https://urlremoved.jira.com/sr/jira.issueviews:searchrequest-xml/temp/SearchRequest.xml?tempMax=100&reset=true&jqlQuery=project+%3D+OIAM+AND+fixVersion+in+%28%221.0.5%22%29+AND+status+in+%28Closed%29+AND+resolution+in+%28Fixed%29+ORDER+BY+priority+DESC%2C+created+DESC
[WARNING] Downloading from JIRA failed. Received: [400]
```
