### ISSUE TITLE
[MCHANGES-353] The RestJiraDownloader ignores the filter property.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#226]
**[Lucas Hahn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lucashahn)** opened **[MCHANGES-353](https://issues.apache.org/jira/browse/MCHANGES-353?redirect=false)** and commented

In RestJiraDownloader the JQL query is created as such:

```
String jqlQuery = new JqlQueryBuilder( log ).urlEncode( false ).project( jiraProject ).fixVersion(getFixFor() ).fixVersionIds( resolvedFixVersionIds ).statusIds( resolvedStatusIds ).priorityIds( resolvedPriorityIds ).resolutionIds( resolvedResolutionIds ).components( resolvedComponentIds ).typeIds( resolvedTypeIds ).sortColumnNames( sortColumnNames ).build();
```

As you can see, the filter method isn't called (unlike the ClassicJiraDownloader). This makes the user unable to specify specific JQL.

I feel like the best solution is if the filter attribute is valued then it creates a completely separate JQL query so it doesn't use any defaults.

Either way, it seems like one should be able to use the filter attribute in some way.

---

**Affects:** 2.11

**Issue Links:**
- [MCHANGES-308](https://issues.apache.org/jira/browse/MCHANGES-308) Support filters when using REST API / JQL
 (_**"duplicates"**_)

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Thomas Lorenz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=leftbit)** commented

Using the Jira Syntax via JQL is essential for custom Jira workflows because the Maven Syntax (specifying _<statusIds>_ etc.) does not work against Jira 6.4.21:

```
[INFO] Generating "JIRA Report" report          --- maven-changes-plugin:2.11:jira-report
[ERROR] Fehler in der JQL-Abfrage: Das Zeichen '?' ist ein reserviertes JQL-Zeichen. Sie müssen es stattdessen in eine Zeichenfolge einfügen oder das Escapezeichen '\u003f' verwenden. (Zeile 1, Zeichen 11)
[WARNING]
org.apache.maven.plugin.MojoExecutionException: Failed to query issues; response 400
        at org.apache.maven.plugin.jira.RestJiraDownloader.reportErrors(RestJiraDownloader.java:201)
        at org.apache.maven.plugin.jira.RestJiraDownloader.doExecute(RestJiraDownloader.java:155)
        at org.apache.maven.plugin.jira.AdaptiveJiraDownloader.doExecute(AdaptiveJiraDownloader.java:47)
        at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:372)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
        at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:224)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
        at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:182)
        at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

similar to MCHANGES-308
