### ISSUE TITLE
[MCHANGES-384] Changes plugin fails when pointed as ASF JIRA instance using http

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#254]
**[Alex O'Ree](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=spyhunter99)** opened **[MCHANGES-384](https://issues.apache.org/jira/browse/MCHANGES-384?redirect=false)** and commented

Coming on over from Apache jUDDI. I'm trying to rig up the changes plugin with the ASF JIRA instance and was presented with the following error message.

Could you use some help fixing this?

[INFO] Generating "JIRA Report" report          --- maven-changes-plugin:2.12.1:jira-report
[INFO] Falling back to RSS for issue download: This JIRA server does not support version 2 of the REST API, which maven-changes-plugin requires.
[WARNING] Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[INFO] Downloading from JIRA at: http://issues.apache.org/jira/secure/IssueNavigator.jspa?view=rss&pid=10401&statusIds=6&resolutionIds=1&sorter/field=created&sorter/order=DESC&sorter/field=priority&sorter/order=DESC&tempMax=100&reset=true&decorator=none
[WARNING]
org.apache.maven.plugin.MojoExecutionException: Failed to parse JIRA XML.
at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:132)
at org.apache.maven.plugin.jira.JiraXML.parseXML(JiraXML.java:108)
at org.apache.maven.plugin.jira.ClassicJiraDownloader.getIssueList(ClassicJiraDownloader.java:446)
at org.apache.maven.plugin.jira.AdaptiveJiraDownloader.getIssueList(AdaptiveJiraDownloader.java:86)
at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:348)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:227)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:329)
at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:181)
at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:135)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.xml.sax.SAXParseException; lineNumber: 75; columnNumber: 1122; The entity name must immediately follow the '&' in the entity reference.
at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:128)
... 31 more

---

**Affects:** 2.12.1

**Issue Links:**
- [MCHANGES-296](https://issues.apache.org/jira/browse/MCHANGES-296) Failed to parse JIRA XML

**Comment by jira-importer** [comment]
**[Alex O'Ree](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=spyhunter99)** commented

Turns out it works just fine. I had the incorrect JIRA url (http and not https). The error message is a little misleading and i'd suggest updating it if possible to detect a url redirect or at least log the http status code
