### ISSUE TITLE
[MCHANGES-406] HttpClient and components

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#276]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** opened **[MCHANGES-406](https://issues.apache.org/jira/browse/MCHANGES-406?redirect=false)** and commented

https://github.com/apache/maven-changes-plugin/pull/9/files

Jenkins seems to fail around TLS versions with the newer ones in JiraUnicodeTestCase. Not clear if that test is a particular problem or just the first one that hits this. 

org.apache.maven.plugin.MojoExecutionException: Couldn't resolve the skin. at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76) Caused by: org.apache.maven.shared.transfer.artifact.resolve.ArtifactResolverException: Failed to read artifact descriptor for org.apache.maven.skins:maven-default-skin:jar:1.0 at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76) Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.maven.skins:maven-default-skin:jar:1.0 at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76) Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.maven.skins:maven-default-skin:pom:1.0 from/to central (

https://repo.maven.apache.org/maven2

): Received fatal alert: protocol_version at org.apache.maven.plugins.jira.JiraUnicodeTestCase.testUnicodeReport(JiraUnicodeTestCase.java:76) Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.maven.skins:maven-default-skin:pom:1.0 from/to central (

https://repo.maven.apache.org/maven2

): Received fatal alert: protocol_version Caused by: org.apache.maven.wagon.TransferFailedException: Received fatal alert: protocol_version Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version

---

**Remote Links:**
- [GitHub Pull Request #57
](https://github.com/apache/maven-changes-plugin/pull/57)

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

should be fixed now, but let's keep an eye on it and ping if it reoccurs.,
