### ISSUE TITLE
[MCHANGES-13] Exception thrown when running changes:announcement-generate

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#298]
**[Brian Bonner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bkbonner)** opened **[MCHANGES-13](https://issues.apache.org/jira/browse/MCHANGES-13?redirect=false)** and commented

Hi,

Maven changes:reports works fine as does site:site.  However, when I try to run m2 changes:announcement-generate I'm getting a stack trace.  It's looking for it in src/main.  The changes reports looks for it in src/changes.

The maven-1 plugin used to look in xdocs/changes.xml

Here's the stacktrace I get when I try to run it:

C:\workspace_paraware\spacestation_applet>m2 -cpu changes:announcement-generate
[INFO] Searching repository for plugin with prefix: 'changes'.
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Building Spacestation
[INFO]    task-segment: [changes:announcement-generate]
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Setting property: file.resource.loader.class => 'org.apache.maven.resourc
e.loader.ProjectResourceLoader'.
[INFO] Setting property: class.resource.loader.class => 'org.apache.velocity.run
time.resource.loader.ClasspathResourceLoader'.
[INFO] Setting property: resource.loader => 'file,class'.
[INFO] **************************************************************
[INFO] Starting Jakarta Velocity v1.4
[INFO] RuntimeInstance initializing.
[INFO] Default Properties File: org\apache\velocity\runtime\defaults\velocity.pr
operties
[INFO] Default ResourceManager initializing. (class org.apache.velocity.runtime.
resource.ResourceManagerImpl)
[INFO] Resource Loader Instantiated: org.apache.maven.resource.loader.ProjectRes
ourceLoader
[INFO] ProjectResourceLoader : initialization starting.
[INFO] path :C:\workspace_paraware\spacestation_applet\src\main\resources\
[INFO] ProjectResourceLoader : adding path 'C:\workspace_paraware\spacestation_a
pplet\src\main\resources\'
[INFO] ProjectResourceLoader : initialization complete.
[INFO] Resource Loader Instantiated: org.apache.velocity.runtime.resource.loader
.ClasspathResourceLoader
[INFO] ClasspathResourceLoader : initialization starting.
[INFO] ClasspathResourceLoader : initialization complete.
[INFO] ResourceCache : initialized. (class org.apache.velocity.runtime.resource.
ResourceCacheImpl)
[INFO] Default ResourceManager initialization complete.
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[INFO] Created: 20 parsers.
[INFO] Velocimacro : initialization starting.
[INFO] Velocimacro : adding VMs from VM library template : VM_global_library.vm
[ERROR] ResourceManager : unable to find resource 'VM_global_library.vm' in any
resource loader.
[INFO] Velocimacro : error using  VM library template VM_global_library.vm : org
.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'V
M_global_library.vm'
[INFO] Velocimacro :  VM library template macro registration complete.
[INFO] Velocimacro : allowInline = true : VMs can be defined inline in templates

[INFO] Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT
replace previous VM definitions
[INFO] Velocimacro : allowInlineLocal = false : VMs defined inline will be  glob
al in scope if allowed.
[INFO] Velocimacro : messages on  : VM system will output logging messages
[INFO] Velocimacro : autoload off  : VM system will not automatically reload glo
bal library macros
[INFO] Velocimacro : initialization complete.
[INFO] Velocity successfully started.
[INFO] [changes:announcement-generate]
java.io.FileNotFoundException: C:\workspace_paraware\spacestation_applet\src\mai
n\changes.xml (The system cannot find the file specified)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.\<init>(FileInputStream.java:106)
at java.io.FileInputStream.\<init>(FileInputStream.java:66)
at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection
.java:69)
at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLCon
nection.java:156)
at java.net.URL.openStream(URL.java:913)
at org.apache.crimson.parser.InputEntity.init(InputEntity.java:209)
at org.apache.crimson.parser.Parser2.parseInternal(Parser2.java:638)
at org.apache.crimson.parser.Parser2.parse(Parser2.java:337)
at org.apache.crimson.parser.XMLReaderImpl.parse(XMLReaderImpl.java:448)

    at javax.xml.parsers.SAXParser.parse(SAXParser.java:345)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:281)
    at org.apache.maven.changes.ChangesXML.<init>(ChangesXML.java:58)
    at org.apache.maven.announcement.AnnouncementMojo.execute(AnnouncementMo

jo.java:162)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:554)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:307)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:217)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:247)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] Creating file...

---

constituent[0]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/commons-cli-1
.0.jar
constituent[1]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/doxia-sink-ap
i-1.0-alpha-4.jar
constituent[2]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/jline-0.9.1.j
ar
constituent[3]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/jsch-0.1.21.j
ar
constituent[4]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-artifac
t-2.0-beta-3.jar
constituent[5]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-artifac
t-manager-2.0-beta-3.jar
constituent[6]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-core-2.
0-beta-3.jar
constituent[7]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-model-2
.0-beta-3.jar
constituent[8]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-monitor
-2.0-beta-3.jar
constituent[9]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-plugin-
api-2.0-beta-3.jar
constituent[10]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-plugin
-descriptor-2.0-beta-3.jar
constituent[11]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-plugin
-parameter-documenter-2.0-beta-3.jar
constituent[12]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-plugin
-registry-2.0-beta-3.jar
constituent[13]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-profil
e-2.0-beta-3.jar
constituent[14]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-projec
t-2.0-beta-3.jar
constituent[15]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-report
ing-api-2.0-beta-3.jar
constituent[16]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-reposi
tory-metadata-2.0-beta-3.jar
constituent[17]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/maven-settin
gs-2.0-beta-3.jar
constituent[18]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/plexus-input
-handler-1.0-alpha-2.jar
constituent[19]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/wagon-file-1
.0-alpha-4.jar
constituent[20]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/wagon-http-l
ightweight-1.0-alpha-4.jar
constituent[21]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/wagon-provid
er-api-1.0-alpha-4.jar
constituent[22]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-B/bin/../lib/wagon-ssh-1.
0-alpha-4.jar

---

java.lang.NullPointerException
at org.apache.maven.announcement.AnnouncementMojo.getLatestRelease(Annou
ncementMojo.java:239)
at org.apache.maven.announcement.AnnouncementMojo.doGenerate(Announcemen
tMojo.java:200)
at org.apache.maven.announcement.AnnouncementMojo.execute(AnnouncementMo
jo.java:164)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:554)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:307)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:217)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:247)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375) 

---
No further details from [MCHANGES-13](https://issues.apache.org/jira/browse/MCHANGES-13?redirect=false)

**Comment by jira-importer** [comment]
**[Allan Q. Ramirez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aramirez)** commented

-fixed..
-the changes.xml should be in the directory of src/changes

**Comment by jira-importer** [comment]
**[Allan Q. Ramirez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aramirez)** commented

try to install the changes plugin with the updateReleaseInfo set to true.

m2 install -DupdateReleaseInfo=true

if this still didnt work please confirm the version of the changes-maven-plugin you used,
it should be 2.0-beta-2-SNAPSHOT
