### ISSUE TITLE
[MCHANGES-12] NPE in Doxia/Printwriter caused by Jira report

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#299]
**[Fabrizio Giustina](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fgiust)** opened **[MCHANGES-12](https://issues.apache.org/jira/browse/MCHANGES-12?redirect=false)** and commented

Probably the NPE should also be handled by doxia, but the jira report is probably trying to call the rawText() method with a null argument.

[INFO] Downloading http://jira.codehaus.org/secure/IssueNavigator.jspa?view=rss&pid=10800&sorter/field=created&sorter/order=DESC&sorter/field=priority&sorter/order=DESC&tempMax=100&reset=true&decorato
r=none
java.lang.NullPointerException
at java.io.PrintWriter.write(PrintWriter.java:401)
at org.codehaus.doxia.module.xhtml.XhtmlSink.write(XhtmlSink.java:837)
at org.codehaus.doxia.module.xhtml.XhtmlSink.rawText(XhtmlSink.java:817)
at org.apache.maven.jira.JiraReportGenerator.sinkCell(JiraReportGenerator.java:158)
at org.apache.maven.jira.JiraReportGenerator.constructDetailRows(JiraReportGenerator.java:103)
at org.apache.maven.jira.JiraReportGenerator.doGenerateReport(JiraReportGenerator.java:30)
at org.apache.maven.jira.JiraMojo.executeReport(JiraMojo.java:170)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:117)
at org.apache.maven.plugins.site.SiteMojo.generateReportsPages(SiteMojo.java:802)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:301)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:452)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---
No further details from [MCHANGES-12](https://issues.apache.org/jira/browse/MCHANGES-12?redirect=false)

**Comment by jira-importer** [comment]
**[Johnny R. Ruiz III](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jruiz)** commented

Submitted Fix.
Please recheck the problem.
Thanks a lot.

**Comment by jira-importer** [comment]
**[Fabrizio Giustina](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fgiust)** commented

fix tested, everything works without problems now. Thanks
