### ISSUE TITLE
[MCHANGES-73] No longer integrates with JIRA

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#391]
**[Immo Huneke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=immohuneke)** opened **[MCHANGES-73](https://issues.apache.org/jira/browse/MCHANGES-73?redirect=false)** and commented

As of this morning (2nd April 2007), the Maven Changes Plugin suddenly stopped working with a fatal error. Nothing about our POMs or the JIRA system used here had changed overnight - yet we were seeing decoding errors in some builds. In an attempt to resolve the situation, we deleted the local Maven repository - with the result that now ALL builds failed during site generation! The configured issue-tracking section of the POM is as follows:

    <issueManagement>
        <system>JIRA</system>
        <url>http://jira-xtools.ldn.swissbank.com:7500/jira/secure/BrowseProject.jspa?pid=10193</url>
    </issueManagement>

We previously had IssueNavigator.jspa, but the result was identical.

Part of the error message is shown below:

artifact org.apache.maven.skins:maven-default-skin: checking for updates from central
Generating /sbclocal/icc/teamcity/buildagent1/ICC_Tools_BuildSystemHooks/SubversionHooks/target/site/jira-report.html
Generate "Jira Report" report.
JIRA lives at: http://jira-xtools.ldn.swissbank.com:7500/jira

---

FATAL ERROR

---

org/apache/commons/codec/DecoderException

---

Trace
java.lang.NoClassDefFoundError: org/apache/commons/codec/DecoderException
at org.apache.commons.httpclient.HttpMethodBase.\<init>(HttpMethodBase.java:217)
at org.apache.commons.httpclient.methods.GetMethod.\<init>(GetMethod.java:88)
at org.apache.maven.plugin.jira.AbstractJiraDownloader.download(AbstractJiraDownloader.java:479)
at org.apache.maven.plugin.jira.AbstractJiraDownloader.doExecute(AbstractJiraDownloader.java:241)
at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:181)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:67)

---

**Affects:** 2.0-beta-2

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

This seems strange. The 2.0-beta-2 release uses commons-httpclient:commons-httpclient:3.0.1, which in turn has a dependency on commons-codec:1.2. So unless you are using some sort of repository proxy there should be no problem for you. If you **are** using a proxy, make sure that you have commons-codec:commons-codec:1.2 in there.
