### ISSUE TITLE
[MCHANGES-88] NoSuchMethodError with maven 2.0.8 when generating changes-report

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#401]
**[Julien Graglia](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jgraglia)** opened **[MCHANGES-88](https://issues.apache.org/jira/browse/MCHANGES-88?redirect=false)** and commented

I create a simple maven2 project, but when i call
mvn -X -e changes:changes-report

I get an error (full log in attachment)

java.lang.NoSuchMethodError: org.apache.maven.doxia.siterenderer.Renderer.createSink(Ljava/io/File;Ljava/lang/String;)Lorg/apache/maven/doxia/siterenderer/sink/SiteRendererSink;
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:63)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)

---

**Affects:** 2.0-beta-3

**Attachments:**
- [AbstractChangesReport.java](https://issues.apache.org/jira/secure/attachment/12714570/AbstractChangesReport.java) (_7.05 kB_)
- [changes.log](https://issues.apache.org/jira/secure/attachment/12714482/changes.log) (_29.33 kB_)
- [changes.zip](https://issues.apache.org/jira/secure/attachment/12714600/changes.zip) (_1.03 kB_)
- [error.log](https://issues.apache.org/jira/secure/attachment/12714505/error.log) (_26.98 kB_)
- [MCHANGES-88-Fix-NoSuchMethodError.patch](https://issues.apache.org/jira/secure/attachment/12714585/MCHANGES-88-Fix-NoSuchMethodError.patch) (_6.08 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12714531/pom.xml) (_1.15 kB_)
- [site.log](https://issues.apache.org/jira/secure/attachment/12714620/site.log) (_41.49 kB_)

**Issue Links:**
- [MCHANGES-105](https://issues.apache.org/jira/browse/MCHANGES-105) java.lang.NoSuchMethodError on changes:jira-report
 (_**"is duplicated by"**_)
- [MPLUGIN-104](https://issues.apache.org/jira/browse/MPLUGIN-104) plugin report broken in 2.4

- [MDEP-160](https://issues.apache.org/jira/browse/MDEP-160) analyze-report fails

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

So if I understand this correctly, we really need a version maven-reporting-impl that uses the same version of doxia as this plugin does. In this case that is 1.0-alpha-9.

Until that is available we need to work around this problem. Copy the execute() method from maven-reporting-impl and modify it so that it only uses doxia-methods that are available in 1.0-alpha-9. This has already been done in MPIR, so an alternative is to copy it from there.

**Comment by jira-importer** [comment]
**[Niall Pemberton](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=niallp)** commented

OK I've created MCHANGES-100
