### ISSUE TITLE
[MCHANGES-105] java.lang.NoSuchMethodError on changes:jira-report

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#413]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** opened **[MCHANGES-105](https://issues.apache.org/jira/browse/MCHANGES-105?redirect=false)** and commented

WAGON_VERSION: 1.0-beta-2
[INFO] ------------------------------------------------------------------------
[INFO] Building WAS6 Maven Plugin
[INFO]    task-segment: [changes:jira-report]
[INFO] ------------------------------------------------------------------------
[INFO] [changes:jira-report]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] org.apache.maven.doxia.siterenderer.Renderer.createSink(Ljava/io/File;Ljava/lang/String;)Lorg/apache/maven/doxia/siterenderer/sink/SiteRendererSink;
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NoSuchMethodError: org.apache.maven.doxia.siterenderer.Renderer.createSink(Ljava/io/File;Ljava/lang/String;)Lorg/apache/maven/doxia/siterenderer/sink/SiteRendererSink;
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:63)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Mon Mar 17 13:07:16 CET 2008
[INFO] Final Memory: 8M/14M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0-beta-3

**Attachments:**
- [error.log](https://issues.apache.org/jira/secure/attachment/12714638/error.log) (_33.75 kB_)

**Issue Links:**
- [MCHANGES-88](https://issues.apache.org/jira/browse/MCHANGES-88) NoSuchMethodError with maven 2.0.8 when generating changes-report
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

http://people.apache.org/repo/m2-snapshot-repository/org/apache/maven/plugins/maven-changes-plugin/2.0-beta-4-SNAPSHOT/
works!
[Although pom in https://svn.apache.org/repos/asf/maven/plugins/trunk/maven-changes-plugin is still marked <version>2.0-SNAPSHOT</version>]

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

Ups - MCHANGES-100 wasn't supposed to be linked - sorry.

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

I think so, yes.
Could you push out a new snapshot so that I can test?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Done.
Please try with maven-changes-plugin-2.0-20080411.201412-2.jar

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

Green!

david@skunk:~/projects/codehaus/mojo/mojo/was6-maven-plugin$ mvn clean org.apache.maven.plugins:maven-changes-plugin:2.0-20080411.201412-2:jira-report -f test_maven_changes_updated_pom.xml
[INFO] Scanning for projects...
WAGON_VERSION: 1.0-beta-2
[INFO] ------------------------------------------------------------------------
[INFO] Building WAS6 Maven Plugin
[INFO]    task-segment: [clean, org.apache.maven.plugins:maven-changes-plugin:2.0-20080411.201412-2:jira-report]
[INFO] ------------------------------------------------------------------------
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-plugin-plugin/2.4.1/maven-plugin-plugin-2.4.1.pom
8K downloaded
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-plugin-plugin/2.4.1/maven-plugin-plugin-2.4.1.jar
30K downloaded
[INFO] [clean:clean]
[INFO] Deleting directory /u/david/projects/codehaus/mojo/mojo/was6-maven-plugin/target
[WARNING] Attempting to build MavenProject instance for Artifact (org.apache.maven.plugins:maven-changes-plugin:2.0-20080411.201412-2) of type: maven-plugin; constructing POM artifact instead.
[INFO] [changes:jira-report]
[INFO] Downloading from JIRA at: http://jira.codehaus.org/secure/IssueNavigator.jspa?view=rss&pid=11730&statusIds=6&resolutionIds=1&sorter/field=created&sorter/order=DESC&sorter/field=priority&sorter/order=DESC&tempMax=100&reset=true&decorator=none
[ERROR] VM #displayTree: error : too few arguments to macro. Wanted 2 got 0
[ERROR] VM #menuItem: error : too few arguments to macro. Wanted 1 got 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23 seconds
[INFO] Finished at: Sat Apr 12 02:29:51 CEST 2008
[INFO] Final Memory: 11M/20M
[INFO] ------------------------------------------------------------------------
david@skunk:~/projects/codehaus/mojo/mojo/was6-maven-plugin$ ls target/
jira-results.xml  site
david@skunk:~/projects/codehaus/mojo/mojo/was6-maven-plugin$ ls target/site/
css  images  jira-report.html
david@skunk:~/projects/codehaus/mojo/mojo/was6-maven-plugin$
