### ISSUE TITLE
[MCHANGES-126] NullPointerException when executing jira-report with JIRA 3.13

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#436]
**[Régis DUTERTRE](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rdutertre)** opened **[MCHANGES-126](https://issues.apache.org/jira/browse/MCHANGES-126?redirect=false)** and commented

I have installed the **new JIRA 3.13** and I cannot generate the jira-report

See stacktrace below:

> java.lang.NullPointerException
> at org.apache.maven.plugin.jira.JiraXML.endElement(JiraXML.java:131)
> at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:633)
> at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1241)
> at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1685)
> at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:368)
> at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:834)
> at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
> at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:148)
> at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1242)
> at javax.xml.parsers.SAXParser.parse(SAXParser.java:375)
> at javax.xml.parsers.SAXParser.parse(SAXParser.java:311)
> at org.apache.maven.plugin.jira.JiraXML.\<init>(JiraXML.java:65)
> at org.apache.maven.plugin.jira.JiraReportGenerator.\<init>(JiraReportGenerator.java:94)
> at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:251)
> at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
> at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
> at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
> at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
> at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:129)
> at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
> at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)

---

**Affects:** 2.0

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Corentin Lonfils](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lonfic)** commented

to fix the problem simply ignore the version number when the parent is not item in the class
org\apache\maven\plugin\jira\JiraXML
...
else if ( qName.equals( "version" ) && currentParent.equals( "item" ))
{
issue.setVersion( currentElement.toString().trim() );
}
...

instead of

else if ( qName.equals( "version" ) )
{
issue.setVersion( currentElement.toString().trim() );
}
...

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Fixed in rev [709990](http://svn.apache.org/viewvc?rev=709990&view=rev).
SNAPSHOT deployed.
As I can't test with this version of jira, if you have any trouble please reopen the issue.
Thanks!
