### ISSUE TITLE
[MCHANGES-137] On the fly generation if changes report fails

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#442]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[MCHANGES-137](https://issues.apache.org/jira/browse/MCHANGES-137?redirect=false)** and commented

Just added 2.1 to my POM. Running site:run seemed fine until I hit refresh. An exeption has been thrown:

```
HTTP ERROR: 500

Error rendering Maven report: Unable to copy static resources.

RequestURI=/changes-report.html
Caused by:

org.apache.maven.doxia.siterenderer.RendererException: Error rendering Maven report: Unable to copy static resources.
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:149)
	at org.apache.maven.plugins.site.webapp.DoxiaFilter.doFilter(DoxiaFilter.java:148)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
	at org.mortbay.jetty.Server.handle(Server.java:313)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:506)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:830)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:381)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:396)
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)
Caused by: org.apache.maven.reporting.MavenReportException: Unable to copy static resources.
	at org.apache.maven.plugin.changes.ChangesMojo.copyStaticResources(ChangesMojo.java:124)
	at org.apache.maven.plugin.changes.ChangesMojo.executeReport(ChangesMojo.java:155)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
	... 17 more

Caused by:

org.apache.maven.reporting.MavenReportException: Unable to copy static resources.
	at org.apache.maven.plugin.changes.ChangesMojo.copyStaticResources(ChangesMojo.java:124)
	at org.apache.maven.plugin.changes.ChangesMojo.executeReport(ChangesMojo.java:155)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
	at org.apache.maven.plugins.site.webapp.DoxiaFilter.doFilter(DoxiaFilter.java:148)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
	at org.mortbay.jetty.Server.handle(Server.java:313)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:506)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:830)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:381)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:396)
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)

Powered by Jetty://
```

This must be some regression, site:run worked perfectly with 2.0.

You may reproduce with https://svn.fckeditor.net/FCKeditor.Java/trunk/ r2713. Set version to 2.1 in POM. and then run mvn site:run. Open up in FF, Introduction > Changes. Hit F5 or Ctrl+F5 > BOOM.

---

**Affects:** 2.1

**Issue Links:**
- [MSITE-406](https://issues.apache.org/jira/browse/MSITE-406) jetty in site run holds unnecessary file lock in windows
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

The fix was made in the Site Plugin, so I'm closing this issue as a duplicate.
