### ISSUE TITLE
[MCHANGES-155] When an empty <action .../> element is present in changes.xml the parser fails

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#457]
**[Martin Vysny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m.vysny)** opened **[MCHANGES-155](https://issues.apache.org/jira/browse/MCHANGES-155?redirect=false)** and commented

With this changelog:

```xml
<document>
	<properties>
		<title>Some changelog</title>
		<author email="mvy@whitestein.com">Martin Vyný</author>
	</properties>
	<body>
	 <release version="1.206.6" date="2009-03-19">
		<action dev="foo" type="update" issue="9966"/>
		<action dev="foo" type="update">Foo</action>
	</body>
</document>
```

mvn changes:announcement-generate fails with

[ERROR] An error occured when parsing the changes.xml file:
org.codehaus.plexus.util.xml.pull.XmlPullParserException: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...\<action dev="foo" type="update">Foo</... `@9`:40)
at org.codehaus.plexus.util.xml.pull.MXParser.nextTag(MXParser.java:1083)
at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseAction(ChangesXpp3Reader.java:388)
at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseRelease(ChangesXpp3Reader.java:716)
at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseBody(ChangesXpp3Reader.java:503)
at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseChangesDocument(ChangesXpp3Reader.java:562)
at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.read(ChangesXpp3Reader.java:1018)
at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.read(ChangesXpp3Reader.java:1049)
at org.apache.maven.plugin.changes.ChangesXML.\<init>(ChangesXML.java:65)
at org.apache.maven.plugin.announcement.AnnouncementMojo.execute(AnnouncementMojo.java:322)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] Creating announcement file from /home/vyzivus/work/lsabpm/lsabpm-1.206.x/src/changes/changes.xml...
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Couldn't find the release '1.206.6' among the supplied releases.

changes-2.0 does not suffer from this problem.

---

**Affects:** 2.1

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

The parser is generated by Modello. Will need to check there as well.

Just out of curiosity, why would you want an action without a description.

**Comment by jira-importer** [comment]
**[Martin Vysny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m.vysny)** commented

I just wanted the "Issue 9966" text to appear as action description. The text is generated by the plugin so I thought that there is no need for a description in changes.xml. However, I learned that it's good to always have a description, even if it is just a name of the bug.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Still valid for `2.11-SNAPSHOT`.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
