### ISSUE TITLE
[MCHANGES-208] XmlPullParserException with changes.xml file

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#503]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** opened **[MCHANGES-208](https://issues.apache.org/jira/browse/MCHANGES-208?redirect=false)** and commented

I have observed a strange behaviour in case of the following.

Given the following changes.xml file:

```xml
<document xmlns="http://maven.apache.org/changes/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/changes/1.0.0 http://maven.apache.org/xsd/changes-1.0.0.xsd">
  <properties>
    <title>Changes report Project</title>
    <author email="zloug@toto.com">Mr Zloug</author>
  </properties>
  <body>
    <release version="1.0" date="2005-01-01" description="First release">
      <action dev="me" type="update" issue="MCHANGES-47" due-to="others" due-to-email="others@users.com">
        <fixes issue="MCHANGES-88"/>
        <fixes issue="JIRA-YYY"/>
        <dueto name="John Doe" email="john@doe.com"/>
        <dueto name="Jane Doe"/>
        Uploaded documentation on how to use the plugin.
      </action>
    </release>
  </body>
</document>
```

This will produce the following problem during site generation:

```
[ERROR] An error occured when parsing the changes.xml file:
org.codehaus.plexus.util.xml.pull.XmlPullParserException: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...\n        Uploaded documentation on how to use the plugin.\n      </... @35:9) 
	at org.codehaus.plexus.util.xml.pull.MXParser.nextTag(MXParser.java:1083)
	at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseAction(ChangesXpp3Reader.java:479)
	at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseRelease(ChangesXpp3Reader.java:802)
	at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseBody(ChangesXpp3Reader.java:587)
	at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.parseChangesDocument(ChangesXpp3Reader.java:640)
	at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.read(ChangesXpp3Reader.java:1104)
	at org.apache.maven.plugins.changes.model.io.xpp3.ChangesXpp3Reader.read(ChangesXpp3Reader.java:1135)
	at org.apache.maven.plugin.changes.ChangesXML.<init>(ChangesXML.java:65)
	at org.apache.maven.plugin.changes.ChangesReportGenerator.<init>(ChangesReportGenerator.java:75)
	at org.apache.maven.plugin.changes.ChangesMojo.executeReport(ChangesMojo.java:256)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:135)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:170)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:330)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:159)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:122)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:107)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:195)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:140)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:451)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:188)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

The above changes.xml files has passed the validation phase without any problems....

The only thing i have changed is to change the order of the entries (moved the text before the other tags):

```xml
  <action dev="me" type="update" issue="MCHANGES-47" due-to="others" due-to-email="others@users.com">
    Uploaded documentation on how to use the plugin.
    <fixes issue="MCHANGES-88"/>
    <fixes issue="JIRA-YYY"/>
    <dueto name="John Doe" email="john@doe.com"/>
    <dueto name="Jane Doe"/>
  </action>
</release>
```

And the site generation will run without any problem.

I have added an integration-test (based on the current trunk r1041074) which produces this situation and the integration test will fail.

---

**Affects:** 2.3

**Attachments:**
- [problem-changes-file.diff](https://issues.apache.org/jira/secure/attachment/12714644/problem-changes-file.diff) (_8.53 kB_)

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

WDYM it has passed the validation phase? Did you run changes:changes-validate?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Yes. I had run the changes-validate with the build process where it originally failed.
And the provided integration test has the validate phase in as well. I did not run it from the command line directly...only as phase during the build.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
