### ISSUE TITLE
[MCHANGES-262] Using custom issue types mapping (MCHANGES-245) throws a llegalArgumentException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#549]
**[Alan Parkinson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alan.parkinson)** opened **[MCHANGES-262](https://issues.apache.org/jira/browse/MCHANGES-262?redirect=false)** and commented

When using the following plugin configuration a IllegalArgumentException is thrown during a execution

\<configuration>
...
\<issueTypes>
\<add>Story\</add>
\</issueTypes>
...
\</configuration>

java.lang.IllegalArgumentException: No enum const class org.apache.maven.plugin.changes.IssueType.STORY
at java.lang.Enum.valueOf(Enum.java:196)
at org.apache.maven.plugin.changes.IssueType.valueOf(IssueType.java:25)
at org.apache.maven.plugin.changes.IssueType.lookupByKey(IssueType.java:48)
at org.apache.maven.plugin.issues.AbstractIssueManagementSystem.applyConfiguration(AbstractIssueManagementSystem.java:69)

---

**Affects:** 2.6

**Attachments:**
- [MCHANGES-262-maven-changes-plugin.patch](https://issues.apache.org/jira/secure/attachment/12714614/MCHANGES-262-maven-changes-plugin.patch) (_4.42 kB_)

2 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Alan Parkinson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alan.parkinson)** commented

Potential fix

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

---

r1328931 | bimargulies | 2012-04-22 14:48:15 -0400 (Sun, 22 Apr 2012) | 2 lines

[MCHANGES-262] Using custom issue types mapping (MCHANGES-245) throws a llegalArgumentException

---
