### ISSUE TITLE
[MCHANGES-296] Failed to parse JIRA XML

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#577]
**[Javier A. Ortiz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=javydreamercsw)** opened **[MCHANGES-296](https://issues.apache.org/jira/browse/MCHANGES-296?redirect=false)** and commented

I guess something changed with the API or returned format.

Here's the configuration in the POM:

\<issueManagement>
\<system>JIRA\</system>
\<url>https://simple-marauroa.jira.com/BrowseProject.jspa?id=10500\</url>
\</issueManagement>

And the report configuration:

\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-changelog-plugin\</artifactId>
\<configuration>
\<useJql>true\</useJql>
\<onlyCurrentVersion>true\</onlyCurrentVersion>
\<jiraUser>realUser\</jiraUser>
\<jiraPassword>realPassword\</jiraPassword>
\</configuration>
\</plugin>

And here's what I get:

org.apache.maven.plugin.MojoExecutionException: Failed to parse JIRA XML.
at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:132)
at org.apache.maven.plugin.jira.JiraXML.parseXML(JiraXML.java:108)
at org.apache.maven.plugin.jira.AbstractJiraDownloader.getIssueList(AbstractJiraDownloader.java:608)
at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:356)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:144)
at org.apache.maven.plugin.changes.AbstractChangesReport.execute(AbstractChangesReport.java:180)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.xml.sax.SAXParseException; lineNumber: 121; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "\</meta>".
at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
at org.apache.maven.plugin.jira.JiraXML.parse(JiraXML.java:128)
... 25 more

---

**Affects:** 2.8

**Issue Links:**
- [MCHANGES-384](https://issues.apache.org/jira/browse/MCHANGES-384) Changes plugin fails when pointed as ASF JIRA instance using http

**Comment by jira-importer** [comment]
**[Javier A. Ortiz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=javydreamercsw)** commented

Noticed this was the wrong plug-in for this issue.
