### ISSUE TITLE
[MCHANGES-307] Check for whitespace on fixVersionIds and statusIds

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changes-plugin#589]
**[Tobias Rübner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tobr)** opened **[MCHANGES-307](https://issues.apache.org/jira/browse/MCHANGES-307?redirect=false)** and commented

On the configuration of the maven changes plugin for the jira-report there are some configuration parameters that do not like whitespace.

I think this will include component, fixVersionIds, statusIds, resolutionIds, typeIds and priorityIds.

The report generation will fail with the follwing error:

```
org.apache.maven.plugin.MojoFailureException: Could not find status  Closed.
	at org.apache.maven.plugin.jira.RestJiraDownloader.resolveOneItem(RestJiraDownloader.java:268)
	at org.apache.maven.plugin.jira.RestJiraDownloader.resolveList(RestJiraDownloader.java:249)
	at org.apache.maven.plugin.jira.RestJiraDownloader.resolveIds(RestJiraDownloader.java:214)
	at org.apache.maven.plugin.jira.RestJiraDownloader.doExecute(RestJiraDownloader.java:129)
	at org.apache.maven.plugin.jira.AdaptiveJiraDownloader.doExecute(AdaptiveJiraDownloader.java:47)
	at org.apache.maven.plugin.jira.JiraMojo.executeReport(JiraMojo.java:367)
...
```

Note the leading whitespace that came through the definition in the pom file.

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-changes-plugin</artifactId>
  <configuration>
    <useJql>true</useJql>
    <jiraUser>${jira.user}</jiraUser>
    <jiraPassword>${jira.password}</jiraPassword>
    <onlyCurrentVersion>true</onlyCurrentVersion>
    <resolutionIds>Fixed</resolutionIds>
    <statusIds>Resolved, Closed</statusIds>
  </configuration>
  <reportSets>
    <reportSet>
      <reports>
        <report>jira-report</report>
      </reports>
    </reportSet>
  </reportSets>
</plugin>

```

I possible solution could be to trim the whitespace.

---

**Affects:** 2.9

**Attachments:**
- [MCHANGES-307.patch](https://issues.apache.org/jira/secure/attachment/12714594/MCHANGES-307.patch) (_1013 bytes_)

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Mirko Friedenhagen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mfriedenhagen)** commented

Fixed with http://svn.apache.org/viewvc?view=revision&revision=1627117, thanks.
